version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
  server:
    build: ../app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: "localhost"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "db"
    command: npm run start:dev

volumes:
  my-db:
